using System;
using System.Diagnostics.CodeAnalysis;

namespace Lithnet.Miiserver.Client
{
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [Flags]
    internal enum MAData : uint
    {
        MA_NAME = 1,
        MA_CATEGORY = 2,
        MA_CNTLRCONFIG = 4,
        MA_SCHEMA = 8,
        MA_PARTITION_DATA = 0x10,
        MA_ATTRINCL = 0x20,
        MA_JOIN = 0x40,
        MA_PROJECT = 0x80,
        MA_DESCRIPTION = 0x100,
        MA_EXPORTATTRFLOW = 0x200,
        MA_PROVCLEANUP = 0x400,
        MA_CONFIGPRIVATE = 0x800,
        MA_ENCRYPTEDATTR = 0x1000,
        MA_COMPONENT_MAPPINGS = 0x2000,
        MA_GUID = 0x4000,
        MA_ASSEMBLY = 0x8000,
        MA_VERSION = 0x10000,
        MA_UISETTINGS = 0x20000,
        MA_FORMATVERSION = 0x40000,
        MA_SDFILTER = 0x80000,
        MA_RUN_DATA = 0x100000,
        MA_CREATION_TIME = 0x200000,
        MA_MODIFICATION_TIME = 0x400000,
        MA_PASSWORD_SYNC_ALLOWED = 0x800000,
        MA_CAPABILITIES = 0x1000000,
        MA_EXPORTTYPE = 0x2000000,
        MA_DNCONSTRUCTION = 0x4000000,
        MA_PASSWORD_SYNC = 0x8000000,
        MA_SUBCATEGORY = 0x10000000,
        MA_LISTNAME = 0x20000000,
        MA_COMPANY_NAME = 0x40000000,
        MA_INTERNAL_VERSION = 0x80000000,
        MA_ALLBITS = MA_NAME | MA_CATEGORY | MA_CNTLRCONFIG | MA_SCHEMA | MA_PARTITION_DATA | MA_ATTRINCL | MA_JOIN | MA_PROJECT | MA_DESCRIPTION |
            MA_EXPORTATTRFLOW | MA_PROVCLEANUP | MA_CONFIGPRIVATE | MA_ENCRYPTEDATTR | MA_COMPONENT_MAPPINGS | MA_GUID | MA_ASSEMBLY | MA_VERSION |
            MA_UISETTINGS | MA_FORMATVERSION | MA_SDFILTER | MA_RUN_DATA | MA_CREATION_TIME | MA_MODIFICATION_TIME | MA_PASSWORD_SYNC_ALLOWED | MA_CAPABILITIES |
            MA_EXPORTTYPE | MA_DNCONSTRUCTION | MA_PASSWORD_SYNC | MA_SUBCATEGORY | MA_LISTNAME | MA_COMPANY_NAME | MA_INTERNAL_VERSION
    }
}
